
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-fluent-pvc-operator-tech-zozo-com-v1alpha1-fluentpvcoperator
  failurePolicy: Fail
  name: mfluentpvcoperator.kb.io
  rules:
  - apiGroups:
    - fluent-pvc-operator.tech.zozo.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - fluentpvcoperators
  sideEffects: None

---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-fluent-pvc-operator-tech-zozo-com-v1alpha1-fluentpvcoperator
  failurePolicy: Fail
  name: vfluentpvcoperator.kb.io
  rules:
  - apiGroups:
    - fluent-pvc-operator.tech.zozo.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - fluentpvcoperators
  sideEffects: None
