# permissions for end users to view fluentpvcs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluentpvc-viewer-role
rules:
- apiGroups:
  - fluent-pvc-operator.tech.zozo.com
  resources:
  - fluentpvcs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - fluent-pvc-operator.tech.zozo.com
  resources:
  - fluentpvcs/status
  verbs:
  - get
