apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sample-app
  name: sample-app
spec:
  replicas: 3
  minReadySeconds: 60
  progressDeadlineSeconds: 600
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
        fluent-pvc-operator.tech.zozo.com/fluent-pvc-name: fluent-pvc-operator-example-log-collection
    spec:
      containers:
        - name: sample-app
          image: fluent-pvc-operator-sample-app:development
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 100m
              memory: 50Mi
          env:
            - name: BENCHMARK_LOGGING_MAX_LOG_COUNT
              value: "10000"
            - name: BENCHMARK_LOGGING_INTERVAL_MILLIS
              value: "1000"
            - name: BENCHMARK_LOGGING_EVENT_NAME
              value: "test-event"
            - name: BENCHMARK_LOGGING_PAYLOAD_KEY1
              value: "myKey1"
            - name: BENCHMARK_LOGGING_PAYLOAD_VALUE1
              value: "myValue1"
      terminationGracePeriodSeconds: 60
