name: build-n-push test

on:
  push:
    branches:
      - 'test-gha'

jobs:
  build-n-push:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Create release YAML
        run: |
          make manifests-release
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: test
          draft: false
          prerelease: false
          generate_release_notes: true
          files: fluent-pvc-operator.yaml
