name: build and push

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE_URI: ghcr.io/${{ github.repository_owner }}/fluent-pvc-operator
      DOCKER_TAG: '0.0.1'
    steps:
    - uses: actions/checkout@v2

    - name: Set up Golang
      uses: actions/setup-go@v2
      with:
        go-version: '1.16'

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Setup tmate session to debug via SSH. See https://github.com/mxschmitt/action-tmate
    # - uses: mxschmitt/action-tmate@v1

    - name: make clean-e2e-test
      run: |
        make clean-e2e-test IMG=${DOCKER_IMAGE_URI}:${DOCKER_TAG}

    - name: make docker-push
      if: github.event_name == 'push'
      run: |
        make docker-push IMG=${DOCKER_IMAGE_URI}:${DOCKER_TAG}
